SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME
FROM
    Polaris.INFORMATION_SCHEMA.COLUMNS
WHERE
       COLUMN_NAME LIKE '%MaterialType%'
    OR COLUMN_NAME LIKE '%PatronCode%'
    OR COLUMN_NAME LIKE '%LoanLimit%'
ORDER BY
    TABLE_NAME,
    ORDINAL_POSITION;
